### ISSUE TITLE
README, AUTHORS

### ISSUE THREAD

**Issue by odelolajosh** [odelolajosh/AirBnB_clone#1]
- Write a README.md:
    - description of the project
    - description of the command interpreter:
        - how to start it
        - how to use it
        - examples
- You should have an AUTHORS file at the root of your repository, listing all individuals having contributed content to the repository. For format, reference [Docker’s AUTHORS page](https://alx-intranet.hbtn.io/rltoken/_8n_z3pf5HWi1l7uv1E9iA)
- You should use branches and pull requests on GitHub - it will help you as team to organize your work

**Comment by odelolajosh** [comment]
Nice work @azconcept-droid

**Comment by azconcept-droid** [comment]
You are welcome BOSS.
